### ISSUE TITLE
Allow perspective_viewer users to subscribe to view updates

### ISSUE THREAD

**Issue by msturdikova** [jpmorganchase/perspective#109]
As a users I want to be notified whenever the underlying view of the perspective viewer is updated so that I can I can perform additional actions when the displayed data changes. The callback in _view.on_update does not seem to expose such functionality and is limited to the scope of the viewer.

**Comment by texodus** [comment]
`perspective-view-update` event now fires when a view's data changes, and a `view` property which refers to the current `perspective.table.view`:

```javascript
let elem = document.getElementById('my-viewer');
elem.addEventListener('perspective-view-update', () => {
    elem.view.to_json(handler);
});
```
