### ISSUE TITLE
Stuck in loading on mobile

### ISSUE THREAD

**Issue by timkpaine** [jpmorganchase/perspective#12]

**Comment by texodus** [comment]
Temporarily fixed - this seems to be a bug in iOS WASM implementation, which I've disabled.  Will revisit this in the future..

**Comment by timkpaine** [comment]
This is resolved on safari for iOS 11.2.5 but I get infinite loading on chrome 64.0.3282.112

**Comment by timkpaine** [comment]
ill send the debug log tonight
