### ISSUE TITLE
Vertical Layout?

### ISSUE THREAD

**Issue by timkpaine** [jpmorganchase/perspective#128]
Is there any ability to configure the chart so the header columns are vertical? I.e. the normal horizontal layout looks like 
<img width="653" alt="screen shot 2018-06-05 at 12 34 58 am" src="https://user-images.githubusercontent.com/3105306/40955566-d5db319a-6858-11e8-8f60-bdf12c3188fe.png">

And i'm looking for something like:a
<img width="105" alt="screen shot 2018-06-05 at 12 41 01 am" src="https://user-images.githubusercontent.com/3105306/40955694-8c832394-6859-11e8-9a4e-62df076fe156.png">

https://github.com/fin-hypergrid/core/issues/723

**Comment by joneit** [comment]
Responded in fin-hypergrid fin-hypergrid/core#723.

**Comment by texodus** [comment]
While I'm open to any feature requests that ultimately make Perspective a better product, I don't think Issues is a good place to discuss them.  We are open to accepting any new plugin implementations into the main project, but we'll need to choose another venue to discuss what the criteria would be.
