### ISSUE TITLE
Column types assumed as int if first value is a whole number

### ISSUE THREAD

**Issue by timkpaine** [jpmorganchase/perspective#13]
If I have a column consisting of values [1.000, 2.5, 3.562, ...] then the column is interpreted as integer instead of float. A (bad) workaround is to increment the first value in the column by a negligible amount (e.g. 0.00000001).

**Comment by tstordyallison** [comment]
I think in this case the only way you are going to get the correct result is to create the table with a schema, rather than rely on type inference. There's only so far down the rabbit hole we can go...

**Comment by timkpaine** [comment]
The json is coming out as 1.000 though. I would get that if it looked like {[1, 2.5, 3.4]} etc where the first value is actually an int.

**Comment by tstordyallison** [comment]
The magic is here: 

https://github.com/jpmorganchase/perspective/blob/828a2614e638bd277863495d3f69f7c2f1586a79/packages/perspective/src/js/perspective.js#L37-L62

It tries to guess the types - but it isn't always going to work (especially in js, where we lack the distinction between an int and a float).

**Comment by timkpaine** [comment]
closing, the solution is really to use a schema
