### ISSUE TITLE
CSV demo failing for multiple people

### ISSUE THREAD

**Issue by ivdelchev** [jpmorganchase/perspective#153]
Hi, 

I've deployed a small demo featuring Perspective and a couple of other libraries and several people report that loading csv data did not work for them. Initially I thought it was on my side, but I cannot reproduce and they also pointed out that https://unpkg.com/@jpmorganchase/perspective-examples@0.1.16/build/csv.html is also failing. Just wanted to let you know and will report if I find anything Perspective-related. 

Here is a bit of discussion if that helps - https://news.ycombinator.com/item?id=17489658

**Comment by texodus** [comment]
Fixed in v0.1.17
