### ISSUE TITLE
xy_line chart ignores `sort` option when plotting lines

### ISSUE THREAD

**Issue by timkpaine** [jpmorganchase/perspective#165]
The orange line's earliest points are 20:42, while the points to its left are 20:44 
![tmp](https://user-images.githubusercontent.com/3105306/43025076-52e70188-8c3e-11e8-80f9-ef1797b00742.gif)

**Comment by texodus** [comment]
Your `x axis` is a string - they are being sorted alphabetically.  You'll need to [provide a schema to the load() function](https://jpmorganchase.github.io/perspective/docs/perspective_api.html#table-1).
