### ISSUE TITLE
superstore arrow demo observable js notebook link share

### ISSUE THREAD

**Issue by RandomFractals** [jpmorganchase/perspective#171]
for anyone who'd like to play with perspective.js live:

https://beta.observablehq.com/@randomfractals/perspective

🤗

**Comment by texodus** [comment]
Thanks for the link!  Still closing this as it is not an issue.

You may also want to consider moving the plugin imports to the header, as they are not registering correctly in your example due to the viewer initialization having already completed.

**Comment by RandomFractals** [comment]
well, yeah, go ahead and close it, but see if  you want to add it to your docs or fork it for others to play with.

thanks

**Comment by timkpaine** [comment]
I think we will eventually have a page for live/production applications using perspective, and gihub doesn't delete old issues so we'll have the link for when we do.
