### ISSUE TITLE
Perspective schema does not map aggregates to their correct types

### ISSUE THREAD

**Issue by sc1f** [jpmorganchase/perspective#183]
When aggregates producing `float` values are applied to integer values, the output numbers are floats while the schema still treats them as integers. 

Issue is visible when hovering over distinct float values, as the tooltip uses the schema to correctly parse data. Because the schema treats `Score 1` as an integer instead of a float average, the tooltip parser cannot treat the value correctly.

Aggregations that produce float values:
- `avg`
- `mean`
- `pct sum parent`
- `pct sum grand total`

---

![screen shot 2018-08-08 at 10 10 23 am](https://user-images.githubusercontent.com/13220267/43842494-7d9030a8-9af3-11e8-9a09-f049435bb920.png)
_Schema shows integer when the data is a float._

![screen shot 2018-08-08 at 10 10 04 am](https://user-images.githubusercontent.com/13220267/43842495-7dab5298-9af3-11e8-9459-d3125d7c265b.png)
_Hover tooltip shows integer when data is a float._

**Comment by texodus** [comment]
Fixed in 0.1.19
