### ISSUE TITLE
[enhancement] cell selection event

### ISSUE THREAD

**Issue by wrthinker** [jpmorganchase/perspective#201]
There're many scenarios that user wants to drill down to a detailed view for one or more selected pivot cells. 

The pivottable.js has provided a preliminary implementation (https://pivottable.js.org/examples/mps_prepop.html) which only supports click event. It would be very useful for perspective to provide more flexible API such as

1. Cell selection change
2. Right click / double click events
3. Context menu if possible

**Comment by texodus** [comment]
Thanks for the report!

Cell interaction has been added in the 0.2.19 release.  It not only returns a consistent event from all plugin types, it also calculates the reciprocal config object from the click event, allowing [linked perspective viewers](https://github.com/jpmorganchase/perspective/blob/master/examples/simple/linked.html) and master-detail views

![linked](https://user-images.githubusercontent.com/60666/53946100-06cc5200-4091-11e9-9c56-e6a5c82c9360.gif)

**Comment by BBassi** [comment]
Can this be done within Jupyterlab
