### ISSUE TITLE
Please, publish to npm the jupyterlab0.34-compatible version

### ISSUE THREAD

**Issue by mprogram** [jpmorganchase/perspective#227]
…not everybody has the `emscripten` compiler installed to build it from the source.

**Comment by timkpaine** [comment]
this is undergoing a fairly substantial set of changes (see [this](https://github.com/jpmorganchase/perspective/pull/222)), should be a release shortly.

**Comment by mprogram** [comment]
Thank you, Tim! I've missed that pull, likely because it was already merged out from my sight. Waiting for a release then, for me it would be quite interesting to try it with your being written Python bindings.

**Comment by timkpaine** [comment]
You can use the perspective from my personal build in the meantime https://github.com/timkpaine/tkp_jupyterlab/tree/master/lab/extensions

**Comment by mprogram** [comment]
Wow, you're a treasure! Thanks really a lot!

**Comment by timkpaine** [comment]
closing for now, please keep an eye out for next release
