### ISSUE TITLE
Computed Column UX bugs

### ISSUE THREAD

**Issue by texodus** [jpmorganchase/perspective#257]
* Column drop target flickers when a column is dragged out of the computed column selector
* Selected columns are cleared when the computation type is changed
* Duplicate named columns silently fail
* Error messages are nice - but IMO we should replace these with just disabling the `Save` button if the inputs are invalid
* Dark theme has some missing colors

**Comment by sc1f** [comment]
Fixed dark theme and removed error messages.

**Comment by texodus** [comment]
Merged
