### ISSUE TITLE
Unable to run perspective in observablehq notebook

### ISSUE THREAD

**Issue by akansal1** [jpmorganchase/perspective#265]
I am trying to run perspective in observablehq notebook, but I am not able to achieve anything.

```javascript
perspective = require("https://unpkg.com/@jpmorganchase/perspective-examples@0.2.0-beta.3/build/perspective.js")
worker=perspective.worker()
table=worker.table(data)
```
data Input

```javascript
data = [
    { x: 1, y: "a", z: true },
    { x: 2, y: "b", z: false },
    { x: 3, y: "c", z: true },
    { x: 4, y: "d", z: false }
]
```
output

``` javascript
  _worker: WebWorker {_worker: Worker}
  _name: "0.9493787914092462" //Number keeps on changing everytime 
```
thanks

**Comment by texodus** [comment]
This is the expected output - your example only creates a `table()` object, and this object is what you see in the output.  Please refer to the [documentation section on querying a table](https://jpmorganchase.github.io/perspective/docs/usage.html#querying-data-with-view) for details on how to proceed from here, e.g. to display the data unmodified as a csv:

<img width="704" alt="screen shot 2018-10-05 at 5 57 15 pm" src="https://user-images.githubusercontent.com/60666/46562012-326fc400-c8c8-11e8-8acf-86ba93adc251.png">

**Comment by akansal1** [comment]
Hi @texodus, thank you

I am trying to use perspective for some data wrangling, but it's performance is slow in comparison alasql or ramda.
Following observablehq notebook on my machine takes more than 10 seconds on just 10000 rows 
https://beta.observablehq.com/@akansal1/untitleds
I was expecting it to be faster than other js libraries.
