### ISSUE TITLE
Errors with IE11, in hypergrid

### ISSUE THREAD

**Issue by voltcode** [jpmorganchase/perspective#27]
using https://jpmorganchase.github.io/perspective/examples/superstore.html in IE 11,

scenario:
1. switch to grid mode
2. unselect country and city
3. move country to columns, after sub-category

results:
1. it's veeery slow - is it because of perspective or because of hypergrid?
2. console shows:
SCRIPT5022: Assertion failed
webcomponents.min.js (11,1555)
View cancelled
View cancelled
Setting up initial schema and data load into HyperGrid

that's probably indicating an internal fault?

**Comment by texodus** [comment]
Thanks for the detailed report, this is very helpful. 

This is indeed an internal fault.  The only way to get real diagnostics in this case is to re-build the library with debug flags, which is currently a bit painful to configure.  I will try to repro.

IE11 will always lag in performance to modern browsers, but we intend to support it functionally until it is dead and buried in industry.

**Comment by texodus** [comment]
I've tested this on the copy of IE11 I have, and only seen out-of-memory errors on large data sets - but this should come with an associated error more detailed than "Assertion Failed."

I've added a build option to generate a debug build, which should give you more information about such issues.  Can you please try running a build as below, and filing a separate report with the stack trace if you encounter any issues?

    `PSP_DEBUG=1 npm start`
