### ISSUE TITLE
Is it possible to make computed columns more flexible, supporting manual input and expressions?

### ISSUE THREAD

**Issue by dknfeiov** [jpmorganchase/perspective#300]
like this 
![computed](https://user-images.githubusercontent.com/8175516/48192172-01305b00-e382-11e8-9c82-091473c6967e.PNG)

**Comment by texodus** [comment]
It is possible, but its not something we're going to be working on in the near future.  There are some design issues to consider in implementing a feature like this, namely that Perspective must have concrete return types.  New functions can be added programmatically but the documentation is sorely lacking and a lot of metadata about the function is required.  The internal implementation of computed columns is likely to change pretty substantially as well, and it would probably make sense for this to be fleshed out before we commit to a concrete UX. 

Give that, I'm going to go ahead and close this issue.  If you'd like to take a crack at implementing this or writing your own external control that integrates via the developer API, feel free to join the [gitter channel](https://gitter.im/jpmorganchase/perspective) and we can discuss how best to approach this.
