### ISSUE TITLE
API differences between viewer component and table.view

### ISSUE THREAD

**Issue by ColinEberhardt** [jpmorganchase/perspective#316]
The 'viewer' component uses plurals:

```
    <perspective-viewer 
        row-pivots='["athlete"]'
        column-pivots='["year"]'>
    </perspective-viewer>
```

However, tree.view uses singular:

https://github.com/jpmorganchase/perspective/tree/master/packages/perspective#view-1

row_pivot, column_pivot, ...

This really threw me for about half an hour, as mentioned to @neilslinger this morning ;-)

**Comment by texodus** [comment]
Thanks for the report - you're right, these are inconsistent.  This has been fixed (and made backwards compatible), and will be released in 0.2.22
