### ISSUE TITLE
load() and update() error for perspective-viewer

### ISSUE THREAD

**Issue by dknfeiov** [jpmorganchase/perspective#321]
The load() function of the view is executed twice, load the table1 and the table2  in turn, the two table has different data structures and some error occurs

1. load(table1), then call update([]) ,error
![image](https://user-images.githubusercontent.com/8175516/48824613-be1db100-ed9f-11e8-89fa-e719ac59b8af.png)

2. old table and new table have at least one identical column, otherwise error, and the old values is not automatically cleared
![image](https://user-images.githubusercontent.com/8175516/48824600-b3631c00-ed9f-11e8-8ad5-1df7944caa64.png)

[Error reproduction](https://jsfiddle.net/dknfeiov/g8h9zbfq/126/)

**Comment by texodus** [comment]
Thanks for the report!  A few issues here -

1. The error message is obviously not ideal, this has been fixed.  I've also made it so `update([])` no longer throws an error at all in #476.
2. `<perspective-viewer>` cannot distinguish via attribute which settings were pre-set before data was loaded, and which are remnants of a previous data load.  You can call the `reset()` method after loading to use defaults.
