### ISSUE TITLE
Paused before potential out-of-memory crash - importing 1m rows from .csv

### ISSUE THREAD

**Issue by kjn2** [jpmorganchase/perspective#341]
Hi, we're trying to import 1 million rows from 500 MB .csv file and getting "Paused before potential out-of-memory crash" error.

Aside from this error, does anyone know what's the limit of rows one can load via .csv (assuming standard Windows/Mac machine of 8 GB of RAM).   

Has anyone done some high-performance testing of the grid using a very large number of rows, e.g. 1m, 2m, 5m, more ?    FYI, Excel allows for 1m rows.  I'd expect this tool to easily go up to 5million (average-sized) rows... is that way too high of an expectation, anybody could comment ?   Thanks !

**Comment by dknfeiov** [comment]
The initial consumption of memory when loading data is very large, causing browser memory to overflow, so the better way is to separate calculations and presentations , and provide calculations through Node. I did this , but that is still not enough to support millons of data.

**Comment by texodus** [comment]
Thanks for the report!

The ultimate dataset size Perspective supports will always be limited be resources allocatable from the browser.  While we've made some substantial improvements to load time and headroom for CSV parsing specifically, and 1mm rows should not really be much of an issue at this point, CSV will always be the slowest and most restrictive way to load data into Perspective - for extremely large datasets, you'll want to encode your data as an [Apache Arrow](https://github.com/apache/arrow) beforehand, which can now even be done [from Perspective itself in node.js](https://github.com/jpmorganchase/perspective/blob/master/docs/perspective.md#to_arrow) if that helps.
