### ISSUE TITLE
Unclear tranpose button

### ISSUE THREAD

**Issue by Ro4052** [jpmorganchase/perspective#347]
The current transpose button uses a cross as its icon. This has lead to some confusion and the intention of the button is unclear at first. Would it be better to have this button as some sort of two way arrow?

![transpose_button_cross](https://user-images.githubusercontent.com/29425751/50212653-788ade80-0373-11e9-80e1-0acef397c6eb.PNG)

**Comment by timkpaine** [comment]
I agree with this

**Comment by texodus** [comment]
Merged & released in 0.2.11
