### ISSUE TITLE
Missing dependencies for perspective

### ISSUE THREAD

**Issue by matt-hooper** [jpmorganchase/perspective#359]
When using perspective in a simple a node.js app, it appears that some dependencies are missing. 
This causes an error when the "require("@jpmorganchase/perspective");" statement is called.

I have the following in my package.json:

```
  "dependencies": {
    "@jpmorganchase/perspective": "^0.2.11"
  }
```

Example code
```
const perspective = require("@jpmorganchase/perspective"); 
console.log("Hello Perspective User");
```

Gives the following error:

> internal/modules/cjs/loader.js:583
>     throw err;
>     ^
> 
> Error: Cannot find module 'tslib'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)

Adding the following dependencies resolves the error:

```
"dependencies": {
    "@jpmorganchase/perspective": "^0.2.11",
    "flatbuffers": "^1.10.2",
    "text-encoding-utf-8": "^1.0.2",
    "tslib": "^1.9.3",
    "ws": "^6.1.2"
  }
```

Result:

> Perspective initialized successfully
> Hello Perspective User

**Comment by timkpaine** [comment]
Thanks for reporting! #364 has been merged
