### ISSUE TITLE
View='horizontal' and view='vertical' less meaningful than view='scatter' and view='line'

### ISSUE THREAD

**Issue by timkpaine** [jpmorganchase/perspective#36]
Maybe hbar/vbar?

**Comment by texodus** [comment]
These HighCharts plugin configurations have been given more descriptive names:
* "y_bar", "y_line", "y_area", "x_bar" for mapping multiple columns to the same axis (row pivots).
* "xy_scatter", "xy_line" for mapping a single column to each chart dimension, e.g. X, Y.
