### ISSUE TITLE
Fresh npm install of @jpmorganchase/perspective, seems to be missing "fast-async" 

### ISSUE THREAD

**Issue by timkpaine** [jpmorganchase/perspective#410]
Might be erroneously listed as a devDependency instead of a regular dependency.

**Comment by texodus** [comment]
I'm pretty confident [this is already fixed](https://github.com/jpmorganchase/perspective/blob/master/packages/perspective-webpack-plugin/package.json#L41) - are you sure you are tested the latest version 0.2.14?

**Comment by timkpaine** [comment]
checking now

**Comment by timkpaine** [comment]
works, closing
