### ISSUE TITLE
perspective-jupyterlab not publishing to dist package

### ISSUE THREAD

**Issue by timkpaine** [jpmorganchase/perspective#442]
Was added here: https://github.com/jpmorganchase/perspective/commit/fe689257923a955221e5332f0130ef07251a6d88#diff-9d8f23b3f4bb47ef250d6f6a116df908

Then you re-broke it here:
https://github.com/jpmorganchase/perspective/commit/627ac4829d056d0932cae5d3586430d494484624#diff-9d8f23b3f4bb47ef250d6f6a116df908

**Comment by texodus** [comment]
Thanks for the report!  This has been "fixed" and was disted in 0.2.19, then superseded by #467
