### ISSUE TITLE
Feature (or example) request: Column repositioning

### ISSUE THREAD

**Issue by jhudson8** [jpmorganchase/perspective#472]
Is there a way to allow columns to be repositioned by the user?  For example, allow drag of column in position 1 to position 3 causing columns to transition from 1, 2, 3 to 2, 3, 1.

If it is possible, would you be able to provide a code example?  Thanks.

**Comment by texodus** [comment]
Yes - just drag the column name, as in the [gif on the README](https://camo.githubusercontent.com/47f52bcd889739a1890b6a3490793b83465aee00/68747470733a2f2f6a706d6f7267616e63686173652e6769746875622e696f2f70657273706563746976652f696d672f64656d6f2e676966) and the example below

![column_reposition](https://user-images.githubusercontent.com/60666/53945447-a557b380-408f-11e9-8c39-31186358731e.gif)
