### ISSUE TITLE
[D3FC] Non-numeric axes on X/Y scatter charts

### ISSUE THREAD

**Issue by texodus** [jpmorganchase/perspective#499]
When a user selects a non-numeric column on an axis of an X/Y scatter chart, is there a way to apply a category axis ala Y scatter chart?  This is helpful when e.g. you want an aggregate which returns a non-numeric (like "unique" or "dominant") on an axis, which is different than the pivoted column - e.g. in this example, the data is grouped by "State", but we have the dominant 'Sub-Category" for each state as a category on the X axis (D3FC on left, HighCharts on right)

<img width="1920" alt="Screen Shot 2019-03-26 at 9 52 19 AM" src="https://user-images.githubusercontent.com/60666/55002501-16162f80-4fad-11e9-805d-2136103131df.png">

**Comment by texodus** [comment]
Similarly - when a `datetime` column is on the axis of an X/Y chart, it should be a datetime axis ala the Y series when pivoted by that column - e.g. in the below, the X axis is showing the datetime stringified and overlapped, rather than the Y line in the following chart.

<img width="1099" alt="Screen Shot 2019-03-26 at 9 55 55 AM" src="https://user-images.githubusercontent.com/60666/55002758-891fa600-4fad-11e9-9e6b-fe4a8238768e.png">
<img width="1041" alt="Screen Shot 2019-03-26 at 9 59 00 AM" src="https://user-images.githubusercontent.com/60666/55002944-d0a63200-4fad-11e9-95cc-590e871e7a7a.png">

**Comment by DevAndyLee** [comment]
I'll take a look. We should be able to detect the desired axis type easily enough, then we'll see if anything else breaks (though I think it should be fine).

**Comment by texodus** [comment]
This is fixed in 511 and was released in 0.2.23!
