### ISSUE TITLE
Column-only views in Hypergrid display an extra empty row

### ISSUE THREAD

**Issue by sc1f** [jpmorganchase/perspective#522]
<img width="727" alt="Screen Shot 2019-04-04 at 4 15 40 PM" src="https://user-images.githubusercontent.com/13220267/55600531-02439980-5722-11e9-8861-ccbed8c4f9f8.png">

In column-only views, Hypergrid displays an extra empty row whereas `to_json` and highcharts displays the same view correctly.

**Comment by texodus** [comment]
Thanks for the report - this is fixed and will be in the 0.2.22 release.
