### ISSUE TITLE
ValueError: "@jpmorganchase/perspective-jupyterlab" is not a valid extension

### ISSUE THREAD

**Issue by boo1245** [jpmorganchase/perspective#53]
Hi,

I received this error when running `jupyter labextension install @jpmorganchase/perspective-jupyterlab` on a valid jupyterlab installation.

Is that an issue you are aware of?

Thanks

**Comment by timkpaine** [comment]
https://github.com/jpmorganchase/perspective/pull/23

**Comment by timkpaine** [comment]
requires a new publish, but in the mean time just install from source

**Comment by timkpaine** [comment]
@boo1245 this should be resolved now

**Comment by boo1245** [comment]
Works. Thanks a lot.

**Comment by timkpaine** [comment]
@boo1245 you may find [this](http://perspective-python.readthedocs.io/en/latest/) helpful
