### ISSUE TITLE
Support for 'delete' row operation

### ISSUE THREAD

**Issue by tstordyallison** [jpmorganchase/perspective#56]
In my streaming data feed I encode the 'insert/update' and 'delete' of the key rows separately. 

I can use perspective to 'insert' (by calling .update) but I can't delete a row by (p)key.  

Can this functionality be added?

**Comment by tstordyallison** [comment]
Any thoughts on the above? Is it something that is planned for the library?

It looks like it supports it internally: 

https://github.com/jpmorganchase/perspective/blob/c7064bcb5a9a988d83bd2c79193acf79a1ed2890/packages/perspective/src/cpp/gnode_state.cpp#L216-L219

Maybe a 'delete(pkey:string)' operation on the table to go with 'update()'?

**Comment by nullrocket** [comment]
I'm also interested in being able to delete rows.

**Comment by texodus** [comment]
This is now implemented in 1.1.10 via the `remove()` method on `perspective.table`, which takes an array of primary keys (the type of the 'index' attribute).
