### ISSUE TITLE
Support for using a 'table' across multiple perspective-viewers

### ISSUE THREAD

**Issue by zemeolotu** [jpmorganchase/perspective#61]
I have a single dataset and I want to have multiple perspective-viewers showing different views of the data (e.g. one showing a chart and the other a grid). Right now, I'm loading the data into all the viewers individually. Is there a better way to do this? Something along the lines of binding a table to multiple perspective-viewers and simply loading data into that single table.

**Comment by texodus** [comment]
Yes - I've added an example to the [README](https://github.com/jpmorganchase/perspective#perspective-viewer-web-component).
