### ISSUE TITLE
Dates become timestamps when pivoting

### ISSUE THREAD

**Issue by timkpaine** [jpmorganchase/perspective#67]
Compare the "index" column to the pivot

![screen shot 2018-03-09 at 11 22 35 am](https://user-images.githubusercontent.com/3105306/37217723-4a9884b8-238c-11e8-8b70-0ca4eb129996.png)
![screen shot 2018-03-09 at 11 23 05 am](https://user-images.githubusercontent.com/3105306/37217727-4c26c998-238c-11e8-9688-b668bf5d23f3.png)

**Comment by timkpaine** [comment]
I assume this is because it is doing a sum across the row, but this is weird in certain contexts like the heat map below, where you want the x axis to be dates

**Comment by texodus** [comment]
This fix is merged and will be released in 0.1.6.  Thanks for the report!
