### ISSUE TITLE
JSON structure not always loadable

### ISSUE THREAD

**Issue by timkpaine** [jpmorganchase/perspective#8]
`"{"x":1,"y":2}"` is not loadable while `"[{"x":1,"y":2}]"` is.

**Comment by texodus** [comment]
When passed an object rather than an Array, it is parsed as a schema for empty an `table`, and `{"x":1,"y":2}` is not a valid schema.  [Table API](https://github.com/jpmorganchase/perspective/tree/master/packages/perspective#table-1)
