### ISSUE TITLE
Uncaught TypeError: Cannot convert "[object Object]" to unsigned int when deleting a table

### ISSUE THREAD

**Issue by ivdelchev** [jpmorganchase/perspective#81]
Hi, and thanks for the great library! I am trying to delete a table to free up the memory but what I see printed in the console is the following:

```
Uncaught TypeError: Cannot convert "[object Object]" to unsigned int
    at Object.toWireType (psp.js:2)
    at Object.unregister_gnode (psp.js:2)
    at _table.delete (perspective.js:678)
    at perspective.js:1092
```
Digging in the toWireType method, brings me to:

```
registerType(primitiveType, {
            name: name,
            "fromWireType": fromWireType,
            "toWireType": (function(destructors, value) {
                if (typeof value !== "number" && typeof value !== "boolean") {
                    throw new TypeError('Cannot convert "' + _embind_repr(value) + '" to ' + this.name)
                }
```

In the CSV there are primitive values such as strings, numbers, booleans and Perspective itself works fine. Any suggestions?

**Comment by nmichaud** [comment]
Hi @ivdelchev, what does your code look like to delete the table?

**Comment by ivdelchev** [comment]
For simplicity, even those two lines result in the above "Uncaught TypeError: Cannot convert "[object Object]" to unsigned int". 

```
let table = worker.table(reader.result);
table.delete();
```

**Comment by texodus** [comment]
I've added tests to verify this does not happen, at least in trivial cases, [almost verbatim as above](https://github.com/jpmorganchase/perspective/pull/115/files).

If you find you still run into this, please open a new issue with a bit more detail about how to recreate - a broken test case would be ideal.
